// Chrome (UI) string dictionary for the two site languages. Only covers
// chrome strings — NOT source text content, which always renders in
// whatever language(s) the per-source/global display settings pick.
// Usage: `t(key, siteLang)` or `t(key, siteLang, {name: "..."})` for the one
// interpolated string (attribution tag).

export const STRINGS = {
  en: {
    sheetTitlePlaceholder: "Untitled Sheet",
    print: "Print / Export",
    addSourcePlaceholder:
      "Genesis 1:1 · Brachot 2a · Rashi al Bereshit · בראשית א:א · a pasted Sefaria link",
    add: "Add",
    settings: "Settings",
    settingsClose: "Close settings",
    titleBarSection: "Source title bar",
    bodySection: "Source text",
    language: "Language",
    languageBoth: "Both",
    languageHebrew: "Hebrew",
    languageEnglish: "English",
    alignment: "Alignment",
    alignmentSides: "Sides (EN left, HE right)",
    alignmentCenter: "Center",
    nikkud: "Nikkud",
    tanakhMode: "Tanakh display mode",
    otherMode: "Other-text display mode",
    modeKlaf: "Klaf (scroll)",
    modeSefer: "Sefer (book)",
    modeSimple: "Simple",
    modeBare: "Bare",
    translationVersion: "Translation version",
    versionJps: "JPS 1985 (default)",
    versionSefariaDefault: "Sefaria default",
    versionCustom: "Custom version title…",
    versionCustomPlaceholder: "Exact Sefaria version title",
    showAttribution: "Show attribution",
    resetAll: "Reset all title/text modifications",
    resetAllConfirm:
      "This will discard every title and text edit on every source in this sheet. Continue?",
    darkModeLight: "Light mode (click for dark)",
    darkModeDark: "Dark mode (click for system)",
    darkModeSystem: "System theme (click for light)",
    siteLanguageToggle: "Switch site language to Hebrew",
    siteLanguageToggleHe: "Switch site language to English",
    keyboardStub: "Hebrew keyboard",
    moveUp: "Move up",
    moveDown: "Move down",
    remove: "Remove",
    noSources: "No sources yet — add one above.",
    editTitle: "Edit title",
    titleEnLabel: "English title",
    titleHeLabel: "Hebrew title",
    resetField: "Reset to original",
    save: "Save",
    cancel: "Cancel",
    editText: "Edit text",
    resetText: "Reset text",
    opTrim: "Trim",
    opElide: "Elide",
    opBracket: "Bracket…",
    opSubstitute: "Substitute…",
    opTextPlaceholder: "Replacement text",
    opConfirm: "Apply",
    opCancel: "Cancel",
    selectWordsHint: "Click a word to select it; shift-click or drag to extend the range.",
    noSelectionHint: "Select a word range to enable an operation.",
    errorTrimNotAtEdge: "Trim can only remove from the very start or end of the text.",
    errorZeroWords: "That would remove all the text — not allowed. Try Elide or Bracket instead.",
    errorEmptyText: "Enter replacement text first.",
    errorInvalidRange: "Select a word range first.",

    // Wave C — sheet structure
    sheetAuthorPlaceholder: "by ___",
    addHeading: "+ Heading",
    addText: "+ Text",
    addSpacer: "+ Spacer",
    spacerSizeS: "S",
    spacerSizeM: "M",
    spacerSizeL: "L",
    headingPlaceholder: "Section heading",
    textBlockPlaceholder: "Free text…",
    deleteBlock: "Delete",
    outlineTitle: "Outline",
    outlineToggleOpen: "Open outline",
    outlineToggleClose: "Close outline",
    outlineEmpty: "Nothing in this sheet yet.",
    outlineExpand: "Show source settings",
    outlineCollapse: "Hide source settings",
    outlineUseGlobal: "— use global setting —",
    outlineResetModifications: "Reset modifications",
    outlineDelete: "Delete",
    outlineDragHandle: "Drag to reorder",
    typeSource: "Source",
    typeHeading: "Heading",
    typeText: "Text",
    typeSpacer: "Spacer",
    undoRemovedToast: "Source removed",
    undo: "Undo",

    // Wave D2 — Hebrew keyboard popup
    keyboardTitle: "Hebrew keyboard",
    keyboardClose: "Close keyboard",
    keyboardLayout: "On-screen layout",
    keyboardLayoutAlephbet: "Alef-bet (alphabetical)",
    keyboardLayoutIsraeli: "Israeli (SI-1452)",
    keyboardLayoutQwerty: "QWERTY (phonetic)",
    keyboardPhysical: "Physical typing (while open)",
    keyboardPhysicalOriginal: "Off — type normally",
    keyboardPhysicalIsraeli: "Israeli (SI-1452)",
    keyboardPhysicalQwerty: "QWERTY (phonetic)",
    keyboardShiftFinalsNote: "Shift + key types the final (sofit) letter, where one exists.",
    keyboardBackspace: "Backspace",
    keyboardSpace: "Space",
    keyboardNoTarget: "Click into a text field, then use the keys below.",
  },
  he: {
    sheetTitlePlaceholder: "דף מקורות ללא שם",
    print: "הדפסה / ייצוא",
    addSourcePlaceholder: "בראשית א:א · ברכות ב. · רש\"י על בראשית · Genesis 1:1",
    add: "הוסף",
    settings: "הגדרות",
    settingsClose: "סגור הגדרות",
    titleBarSection: "שורת כותרת המקור",
    bodySection: "טקסט המקור",
    language: "שפה",
    languageBoth: "שתיהן",
    languageHebrew: "עברית",
    languageEnglish: "אנגלית",
    alignment: "יישור",
    alignmentSides: "צדדים (אנגלית משמאל, עברית מימין)",
    alignmentCenter: "מרכז",
    nikkud: "ניקוד",
    tanakhMode: "מצב תצוגת תנ\"ך",
    otherMode: "מצב תצוגת טקסטים אחרים",
    modeKlaf: "קלף (מגילה)",
    modeSefer: "ספר",
    modeSimple: "פשוט",
    modeBare: "חשוף",
    translationVersion: "גרסת תרגום",
    versionJps: "JPS 1985 (ברירת מחדל)",
    versionSefariaDefault: "ברירת המחדל של ספריא",
    versionCustom: "כותרת גרסה מותאמת אישית…",
    versionCustomPlaceholder: "כותרת גרסה מדויקת בספריא",
    showAttribution: "הצג ייחוס",
    resetAll: "אפס את כל שינויי הכותרות/הטקסט",
    resetAllConfirm:
      "פעולה זו תבטל כל עריכת כותרת וטקסט בכל מקור בדף זה. להמשיך?",
    darkModeLight: "מצב בהיר (לחץ למצב כהה)",
    darkModeDark: "מצב כהה (לחץ למצב מערכת)",
    darkModeSystem: "ערכת נושא של המערכת (לחץ למצב בהיר)",
    siteLanguageToggle: "עבור לשפת ממשק עברית",
    siteLanguageToggleHe: "עבור לשפת ממשק אנגלית",
    keyboardStub: "מקלדת עברית",
    moveUp: "הזז למעלה",
    moveDown: "הזז למטה",
    remove: "הסר",
    noSources: "אין עדיין מקורות — הוסף אחד למעלה.",
    editTitle: "ערוך כותרת",
    titleEnLabel: "כותרת באנגלית",
    titleHeLabel: "כותרת בעברית",
    resetField: "אפס למקור",
    save: "שמור",
    cancel: "בטל",
    editText: "ערוך טקסט",
    resetText: "אפס טקסט",
    opTrim: "קיצוץ",
    opElide: "השמטה",
    opBracket: "סוגריים…",
    opSubstitute: "החלפה…",
    opTextPlaceholder: "טקסט חלופי",
    opConfirm: "החל",
    opCancel: "בטל",
    selectWordsHint: "לחץ על מילה לבחירה; שיפט-קליק או גרירה להרחבת הטווח.",
    noSelectionHint: "בחר טווח מילים כדי להפעיל פעולה.",
    errorTrimNotAtEdge: "אפשר לקצץ רק מתחילת הטקסט ממש או מסופו ממש.",
    errorZeroWords: "פעולה זו תמחק את כל הטקסט — אסור. נסה השמטה או סוגריים במקום זאת.",
    errorEmptyText: "יש להזין טקסט חלופי תחילה.",
    errorInvalidRange: "יש לבחור טווח מילים תחילה.",

    // Wave C — sheet structure
    sheetAuthorPlaceholder: "מאת ___",
    addHeading: "+ כותרת",
    addText: "+ טקסט",
    addSpacer: "+ רווח",
    spacerSizeS: "ק",
    spacerSizeM: "ב",
    spacerSizeL: "ג",
    headingPlaceholder: "כותרת קטע",
    textBlockPlaceholder: "טקסט חופשי…",
    deleteBlock: "מחק",
    outlineTitle: "תוכן עניינים",
    outlineToggleOpen: "פתח תוכן עניינים",
    outlineToggleClose: "סגור תוכן עניינים",
    outlineEmpty: "אין עדיין תוכן בדף זה.",
    outlineExpand: "הצג הגדרות מקור",
    outlineCollapse: "הסתר הגדרות מקור",
    outlineUseGlobal: "— השתמש בהגדרה הכללית —",
    outlineResetModifications: "אפס שינויים",
    outlineDelete: "מחק",
    outlineDragHandle: "גרור כדי לסדר מחדש",
    typeSource: "מקור",
    typeHeading: "כותרת",
    typeText: "טקסט",
    typeSpacer: "רווח",
    undoRemovedToast: "המקור הוסר",
    undo: "בטל",

    // Wave D2 — Hebrew keyboard popup
    keyboardTitle: "מקלדת עברית",
    keyboardClose: "סגור מקלדת",
    keyboardLayout: "פריסה על המסך",
    keyboardLayoutAlephbet: "אלף-בית (לפי סדר אלפביתי)",
    keyboardLayoutIsraeli: "ישראלית (SI-1452)",
    keyboardLayoutQwerty: "QWERTY (פונטית)",
    keyboardPhysical: "הקלדה פיזית (בזמן שהמקלדת פתוחה)",
    keyboardPhysicalOriginal: "כבוי — הקלד כרגיל",
    keyboardPhysicalIsraeli: "ישראלית (SI-1452)",
    keyboardPhysicalQwerty: "QWERTY (פונטית)",
    keyboardShiftFinalsNote: "מקש Shift + אות מקליד אות סופית, במידה וקיימת.",
    keyboardBackspace: "מחיקה לאחור",
    keyboardSpace: "רווח",
    keyboardNoTarget: "לחץ על שדה טקסט, ואז השתמש במקשים למטה.",
  },
};

export function t(key, siteLang, vars) {
  const dict = STRINGS[siteLang] || STRINGS.en;
  let str = dict[key] != null ? dict[key] : STRINGS.en[key] != null ? STRINGS.en[key] : key;
  if (vars) {
    for (const k of Object.keys(vars)) {
      str = str.replace(new RegExp(`\\{${k}\\}`, "g"), vars[k]);
    }
  }
  return str;
}
